-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO AS R1
WHERE FAVORITES = (SELECT MAX(FAVORITES) FROM REST_INFO AS R2
                  WHERE R1.FOOD_TYPE = R2.FOOD_TYPE)
ORDER BY FOOD_TYPE DESC;