-- 코드를 입력하세요
SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, RR.REVIEW_DATE
FROM REST_REVIEW AS RR
JOIN MEMBER_PROFILE AS MP
ON RR.MEMBER_ID = MP.MEMBER_ID
WHERE RR.MEMBER_ID = (SELECT RR2.MEMBER_ID 
                      FROM REST_REVIEW AS RR2 
                      GROUP BY RR2.MEMBER_ID 
                      ORDER BY COUNT(*) 
                      DESC LIMIT 1)
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT;