-- CASE, WHEN, THEN 사용시 마지막에 END 꼭 작성하기!

select BOARD_ID, WRITER_ID, TITLE, PRICE, 
(CASE WHEN STATUS = "SALE" THEN "판매중" 
 WHEN STATUS = "RESERVED" THEN "예약중" 
 WHEN STATUS = "DONE" THEN "거래완료"
END ) STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE = "2022-10-05"
ORDER BY BOARD_ID DESC;